### ISSUE TITLE
Jdk 9/10 fails to build

### ISSUE THREAD

**Issue by proubatsis** [OpenLiberty/guide-microprofile-opentracing#24]
This is the error from `mvn clean install` on travis:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.748 sec <<< FAILURE! - in it.io.openliberty.guides.system.SystemEndpointTest
testGetProperties(it.io.openliberty.guides.system.SystemEndpointTest)  Time elapsed: 0.701 sec  <<< ERROR!
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.apache.cxf.service.model.EndpointInfo.setAddress(EndpointInfo.java:97)
	at org.apache.cxf.jaxrs.AbstractJAXRSFactoryBean.createEndpointInfo(AbstractJAXRSFactoryBean.java:150)
	at org.apache.cxf.jaxrs.AbstractJAXRSFactoryBean.createEndpoint(AbstractJAXRSFactoryBean.java:219)
	at org.apache.cxf.jaxrs.client.JAXRSClientFactoryBean.createWebClient(JAXRSClientFactoryBean.java:220)
	at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.initTargetClientIfNeeded(ClientImpl.java:357)
	at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.request(ClientImpl.java:260)
	at it.io.openliberty.guides.system.SystemEndpointTest.testGetProperties(SystemEndpointTest.java:39)
Results :
Tests in error: 
  SystemEndpointTest.testGetProperties:39 » NoClassDefFound javax/xml/bind/JAXBE...
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

https://travis-ci.org/OpenLiberty/guide-microprofile-opentracing/jobs/394283521

**Comment by proubatsis** [comment]
**Tested with:**

* Open JDK 9
* Oracle JDK 9
* Open JDK 10
* Oracle JDK 10

**Comment by proubatsis** [comment]
**Build:** 18.0.0.1/wlp-1.0.20.cl180120180309-2209
