### ISSUE TITLE
Comments on OpenTracing guide...

### ISSUE THREAD

**Issue by kwsutter** [OpenLiberty/guide-microprofile-opentracing#3]
Comments from @njr-11 while reviewing the guide for Think...

..., I tried out the following (internal) guide and have these comments,
https://qa-guides.mybluemix.net/guides/microprofile-opentracing.html

Minor grammar error: missing space between application.Note

Name of git project appears to be
https://github.com/OpenLiberty/draft-guide-microprofile-opentracing.git
rather than the value that is shown in the guide:
https://github.com/openliberty/guide-microprofile-opentracing.git 

Instructions state: "Navigate to your Zipkin server to verify"
The guide needs to explain precisely how to do so - what are we looking for, where to find it, what should it look like? It should not presume that everyone already knows Zipkin and where to find things in it. Additionally, the guide never explicitly told me to start the zipkin server, only to install it, so a user might not even have it started at this point.

The following URL
http://localhost:9081/inventory/systems/localhost
results in an error:
ERROR: Unknown hostname or the system service may not be running on localhost

Note that the previous URL, http://localhost:9081/inventory/systems worked just fine.

The guide has an incomplete sentence that suggests part of the document is missing,
"Note that this user feature also comes with the"  [no text is present after this point until the next paragraph]

The guide says,
"If the annotation is placed on a method, then it overwrites the class annotation if one exists".  I think you mean overrides, not overwrites.

**Comment by Kubik42** [comment]
Regarding the error you encountered, its weird but it seems like maven is only executing the start-server goal for on of the services. As a temporary fix, run `mvn install liberty:start-server` separately as `mvn install` and `mvn libertry:start-server`

**Comment by njr-11** [comment]
The above worked for 'finish', so I decided to try the steps for 'start'.

On to the next error, which is:

[ERROR] Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:2.0:install-server (install-liberty) on project system-service: Can't get https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2018-02-21_-1508/openliberty-all-18.0.0.1-20180221-1457.zip to /Users/njr/.m2/repository/wlp-cache/openliberty-all-18.0.0.1-20180221-1457.zip -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:2.0:install-server (install-liberty) on project system-service: Can't get https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2018-02-21_-1508/openliberty-all-18.0.0.1-20180221-1457.zip to /Users/njr/.m2/repository/wlp-cache/openliberty-all-18.0.0.1-20180221-1457.zip
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Can't get https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2018-02-21_-1508/openliberty-all-18.0.0.1-20180221-1457.zip to /Users/njr/.m2/repository/wlp-cache/openliberty-all-18.0.0.1-20180221-1457.zip
	at org.codehaus.mojo.pluginsupport.MojoSupport.execute(MojoSupport.java:137)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: Can't get https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2018-02-21_-1508/openliberty-all-18.0.0.1-20180221-1457.zip to /Users/njr/.m2/repository/wlp-cache/openliberty-all-18.0.0.1-20180221-1457.zip
	at net.wasdev.wlp.ant.install.InstallLibertyTask.execute(InstallLibertyTask.java:52)
	at net.wasdev.wlp.maven.plugins.BasicSupport.installFromArchive(BasicSupport.java:379)
	at net.wasdev.wlp.maven.plugins.BasicSupport.installServerAssembly(BasicSupport.java:287)
	at net.wasdev.wlp.maven.plugins.server.PluginConfigSupport.installServerAssembly(PluginConfigSupport.java:71)
	at net.wasdev.wlp.maven.plugins.server.InstallServerMojo.doExecute(InstallServerMojo.java:30)
	at org.codehaus.mojo.pluginsupport.MojoSupport.execute(MojoSupport.java:122)
	... 22 more
Caused by: Can't get https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2018-02-21_-1508/openliberty-all-18.0.0.1-20180221-1457.zip to /Users/njr/.m2/repository/wlp-cache/openliberty-all-18.0.0.1-20180221-1457.zip
	at org.apache.tools.ant.taskdefs.Get$GetThread.downloadFile(Get.java:735)
	at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:586)
	at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:569)

If I browse to,
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/
I don't see any build named 2018-02-21_-1508, and the oldest there looks to be 2018-03-06_2220.  Is an old build number hard-coded into this guide, which has since been removed?

**Comment by kwsutter** [comment]
@njr-11 The 18.0.0.1 driver had to be re-built over the weekend, thus negating the previous nightly drivers that this guide was pointing at.  @Kubik42 is updating the draft instructions to allow the use of a newer driver.

**Comment by Kubik42** [comment]
I updated the doc and the poms, you'll have to download a gm build and place it under <guide dir>/wlp.zip. The link for the build is here: https://rtpgsa.ibm.com/projects/l/liberty.build/liberty/WAS85.LIBERTY/daily/cl180120180309-2209.27.linux/linux/zipper/externals/installables/openliberty-18.0.0.1-20180309-2316.zip

**Comment by Kubik42** [comment]
Figured out why the 9080 endpoint wasn't starting. Because this is a multi module project, and project 2 tests depend on project 1 running. Project 2 actually starts and stops project 1 during its test phase. So running `mvn install liberty:start-server` will start project 1, but then it will be stopped by project 2 when that one goes through its test phase.

**Comment by Kubik42** [comment]
everything addressed as of fb807a28ba94105a28b83615036d498f2d3ae952

**Comment by Kubik42** [comment]
Do you have any other suggestions @kwsutter @njr-11 ?
